anguage: python

python:
  - 3.4

services: postgresql

env:
  - DJANGO=1.7

branches:
  only:
    - master
    - develop

before_install:
  - cp dpnode/dpnode/localsettings_dist.py dpnode/dpnode/localsettings.py
  - export DJANGO_SETTINGS_MODULE=dpnode.settings
  - export PYTHONPATH=$HOME/builds/APTrust/EarthDiver
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - python dpnode/manage.py syncdb --noinput
  - python dpnode/manage.py migrate --noinput

script:
  - cd dpnode && python manage.py test

notifications:
  email:
    recipients:
      - "scott.turnbull@aptrust.org"
    on_success: "change"
    on_failure: "always"